### ISSUE TITLE
TODO: publish to npm

### ISSUE THREAD

**Issue by asukaminato0721** [open-spaced-repetition/fsrs-rs-nodejs#5]

**Comment by asukaminato0721** [comment]
https://github.com/orgs/napi-rs/discussions/2087

**Comment by asukaminato0721** [comment]
https://www.npmjs.com/package/fsrs-rs-nodejs

**Comment by ishiko732** [comment]
The corresponding binary file has not been published on npm. :(

![image](https://github.com/user-attachments/assets/24df361d-9fd7-4e6e-a500-ae83253b760c)
![image](https://github.com/user-attachments/assets/5438de03-eb76-4a37-ba02-d8196ed081db)

**Comment by ishiko732** [comment]
maybe: https://github.com/parcel-bundler/lightningcss/blob/84ebbed7c4645da50ce9dee14001779531366cd6/.github/workflows/release.yml#L264-L271

**Comment by asukaminato0721** [comment]
done

**Comment by asukaminato0721** [comment]
never mind, hope next time won't 429. at least more package uploaded successfully.

**Comment by ishiko732** [comment]
![image](https://github.com/user-attachments/assets/13898c1e-1fe6-4e14-b194-3b64a4714fe2)

ok,can be invoked by installing dependencies.
